### ISSUE TITLE
Blog link

### ISSUE THREAD

**Issue by favio41** [colinodell/git-amend-old#2]
Hi, trying to use git fixup, but the blog doesn't have the code for the alias. (Using chrome on mac)

**Comment by colinodell** [comment]
:scream: It looks like my embedded gist stopped showing up in the post! Dang CMS security settings.  I've fixed that and duplicated the aliases in each section, just in case it happens again.

Blog post: https://www.colinodell.com/blog/201803/four-useful-git-aliases

Gist: https://gist.github.com/colinodell/89ee20346628d4f31aca4a7118b159a0

Thank you so much for catching this!!
